package com.techullurgy.rubikscube.utils

enum class GameMove {
    FRONT_CLOCKWISE,
    FRONT_ANTICLOCKWISE,
    BACK_CLOCKWISE,
    BACK_ANTICLOCKWISE,
    UP_CLOCKWISE,
    UP_ANTICLOCKWISE,
    DOWN_CLOCKWISE,
    DOWN_ANTICLOCKWISE,
    LEFT_CLOCKWISE,
    LEFT_ANTICLOCKWISE,
    RIGHT_CLOCKWISE,
    RIGHT_ANTICLOCKWISE
}